package com.rentalapp.rentalapi.model;

import java.time.LocalDateTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/** Entity representing a message sent by a user to a rental owner */
@Data
@Entity
@AllArgsConstructor
@NoArgsConstructor
@Table(name = "messages")
public class Message {

    /** Primary key, autogenerated */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /** ID of the rental property associated with the message */
    @ManyToOne
    @JoinColumn(name = "rental_id")
    private Rental rental;

    /** ID of the rental owner receiving the message */
    @ManyToOne
    @JoinColumn(name = "user_id")
    private User owner;

    /** Content of the message send by the user */
    private String message;

    /** Timestamp of creation, set once and not updatable. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /** Timestamp of the last update. */
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    /** Initializes `createdAt` and `updatedAt` before persisting */
    @PrePersist
    protected void onCreate() {
        this.createdAt = LocalDateTime.now();
        this.updatedAt = this.createdAt;
    }
}
