package com.rentalapp.rentalapi.dto.response;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import lombok.NonNull;
import lombok.RequiredArgsConstructor;

/**
 * DTO with the token for authentificated user
 */
@Data
@RequiredArgsConstructor
public class TokenResponse {

    /**
     * The token generated by JWTService
     */
    @NonNull
    @Schema(example = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...")
    private String token;

}
